<?php

namespace Escher;


class Exception extends \Exception
{
    const CODE_MISSING_AUTH = 1001;
    const CODE_MISSING_HEADER_PARAM = 1100;
    const CODE_MISSING_QUERY_KEY_PARAM = 1101;
    const CODE_MISSING_HOST_HEADER = 1102;
    const CODE_FORMAT_INVALID_DATE_HEADER_GMT = 2001;
    const CODE_FORMAT_INVALID_AUTH_HEADER = 2002;
    const CODE_FORMAT_INVALID_QUERY_KEY = 2003;
    const CODE_FORMAT_INVALID_DATE_HEADER = 2004;
    const CODE_ARGUMENT_INVALID_ESCHER_KEY = 3001;
    const CODE_ARGUMENT_INVALID_HASH = 3002;
    const CODE_ARGUMENT_INVALID_CREDENTIAL_SCOPE = 3003;
    const CODE_ARGUMENT_INVALID_DATE = 3004;
    const CODE_NOT_SIGNED_HOST_HEADER = 4001;
    const CODE_NOT_SIGNED_HEADER_PARAM = 4002;
    const CODE_EXPIRED_TIME_RANGE = 5001;
    const CODE_SIGNATURE_NOT_MATCH = 6001;
}
